"""IATA code to city/country lookup, plus the airport-size signal discovery seeding uses.

The table is a committed build artifact (`data/airports.v3.json`), regenerated by
`data/build_airports.py` from OurAirports + Travelpayouts — same pattern as
`countries.json`. Everything here degrades to the bare IATA code if the file is missing,
so a cold checkout still runs.

An entry is `{city, country}` always, plus `{name, type, scheduled, lat, lon}` for a
real airport (metro codes like LON / NYC carry only city + country).
"""
from __future__ import annotations

import json
import threading
from typing import Any

from config import DATA_DIR

_TABLE_FILE = DATA_DIR / "airports.v3.json"

_lock = threading.Lock()
_index: dict[str, dict[str, Any]] | None = None


def load() -> dict[str, dict[str, Any]]:
    global _index
    with _lock:
        if _index is None:
            try:
                _index = json.loads(_TABLE_FILE.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                _index = {}
        return _index


# Full ISO 3166-1 alpha-2 -> {name, continent, subregion}, derived from mledoze/countries
# with travel-taxonomy overrides. Regenerate with `py -3 data/build_countries.py`.
_COUNTRIES_FILE = DATA_DIR / "countries.json"
_countries: dict[str, dict[str, str]] | None = None


def _country_table() -> dict[str, dict[str, str]]:
    global _countries
    if _countries is None:
        try:
            _countries = json.loads(_COUNTRIES_FILE.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            _countries = {}
    return _countries


def country_name(code: str) -> str:
    return _country_table().get((code or "").upper(), {}).get("name", "")


def region_of(code: str) -> tuple[str, str]:
    """(continent, subregion) for an ISO alpha-2 country code, or ('', '') if unknown."""
    entry = _country_table().get((code or "").upper())
    return (entry["continent"], entry["subregion"]) if entry else ("", "")


def taxonomy() -> list[dict[str, Any]]:
    """The region tree: continents -> subregions -> countries, for /api/regions."""
    tree: dict[str, dict[str, list[dict[str, str]]]] = {}
    for code, e in _country_table().items():
        cont, sub = e["continent"], e["subregion"]
        if cont in ("", "Antarctic"):
            continue
        tree.setdefault(cont, {}).setdefault(sub, []).append({"code": code, "name": e["name"]})
    return [
        {
            "continent": cont,
            "subregions": [
                {"name": sub, "countries": sorted(cs, key=lambda c: c["name"])}
                for sub, cs in sorted(subs.items())
            ],
        }
        for cont, subs in sorted(tree.items())
    ]


def describe(code: str) -> dict[str, Any]:
    entry = load().get((code or "").upper())
    if not entry:
        return {"city": (code or "").upper(), "country": ""}
    # A handful of rows carry an admin-district parenthetical in `city` ("Paris (Orly,
    # Val-de-Marne)"); trim it for display. Copy so the cached table stays untouched.
    city = (entry.get("city") or "")
    if " (" in city:
        entry = {**entry, "city": city.split(" (")[0].strip()}
    return entry


# Best-hub-first ordinal for discovery seeding. A metro code (LON, NYC) has no `type`
# and sorts with the mediums — it is still a fine thing to probe.
_TIER_RANK = {"large": 0, "medium": 1, "small": 3}


_hub_index: list[tuple[str, dict[str, Any]]] | None = None


def _hubs() -> list[tuple[str, dict[str, Any]]]:
    """Scheduled large/medium airports, code + entry, best hubs first. Cached."""
    global _hub_index
    if _hub_index is None:
        rows = [
            (code, e) for code, e in load().items()
            if e.get("scheduled") and e.get("type") in ("large", "medium")
        ]
        rows.sort(key=lambda ce: (_TIER_RANK.get(ce[1].get("type"), 2), ce[1].get("city") or "", ce[0]))
        _hub_index = rows
    return _hub_index


def _country_hub(cc: str) -> str | None:
    """The busiest scheduled hub in a country, or None. `_hubs()` is already best-first."""
    cc = (cc or "").upper()
    for code, e in _hubs():
        if (e.get("country") or "").upper() == cc:
            return code
    return None


def _clean_city(entry: dict[str, Any]) -> str:
    """City name without the admin-district parenthetical some rows carry ('Paris (Orly…')."""
    return ((entry.get("city") or "").split(" (")[0]).strip()


def _airport_label(entry: dict[str, Any]) -> str:
    """The airport's own name minus the redundant city prefix, e.g. 'Suvarnabhumi'."""
    name = (entry.get("name") or "").strip()
    city = _clean_city(entry)
    if city and name.lower().startswith(city.lower()) and len(name) > len(city):
        name = name[len(city):].lstrip(" -–")
    return name if name and name.lower() not in ("airport", "international airport") else (entry.get("name") or "")


def search_places(query: str, limit: int = 12) -> list[dict[str, Any]]:
    """Typeahead over countries and scheduled-hub airports for the destination combobox.

    Ranks exact IATA codes first, then prefix matches, then substrings; a short query that
    names a country surfaces the country row above its airports so you can pick the whole
    place in one go.
    """
    q = (query or "").strip().lower()
    if len(q) < 2:
        return []
    out: list[tuple[int, str, dict[str, Any]]] = []

    for code, e in _country_table().items():
        name = (e.get("name") or "")
        nl = name.lower()
        if e.get("continent") in ("", "Antarctic"):
            continue
        if q == code.lower():
            rank = 0
        elif nl.startswith(q):
            rank = 1
        elif q in nl:
            rank = 4
        else:
            continue
        out.append((rank, name, {
            "kind": "country", "code": code.upper(), "label": name,
            "sub": " · ".join(p for p in (e.get("continent"), e.get("subregion")) if p),
            # The busiest hub in the country, so an origin combobox can resolve a country
            # pick to a single departure airport.
            "hub": _country_hub(code),
        }))

    for code, e in _hubs():
        city = _clean_city(e)
        name = (e.get("name") or "").strip()
        cl, nl, cd = city.lower(), name.lower(), code.lower()
        if q == cd:
            rank = 0
        elif cl.startswith(q) or nl.startswith(q):
            rank = 2
        elif q in cl or q in nl:
            rank = 5
        else:
            continue
        # A large hub outranks a medium one at the same match strength.
        rank = rank * 2 + _TIER_RANK.get(e.get("type"), 2)
        cc = (e.get("country") or "").upper()
        out.append((rank, city or code, {
            "kind": "airport", "code": code.upper(), "label": city or code,
            "sub": " · ".join(p for p in (_airport_label(e), country_name(cc)) if p),
        }))

    out.sort(key=lambda r: (r[0], r[1]))
    return [item for _, _, item in out[:limit]]


def shortlist(country_codes: "Any", limit: int = 40, hubs_only: bool = True) -> list[str]:
    """IATA codes in the given ISO alpha-2 countries, best hubs first.

    Discovery seeding (`board._seed_candidates`) probes this list for a live fare when the
    board provider's own discovery returns too few destinations inside a region filter.
    Ordered by scheduled service, then airport size; one code per airport, capped at
    `limit` so the probe stays cheap. `hubs_only` drops the small airstrips — nobody flies
    a board-worthy international trip from those, and probing them just wastes calls.
    """
    want = {(c or "").upper() for c in country_codes}
    if not want:
        return []
    rows = []
    for code, e in load().items():
        if e.get("country") not in want:
            continue
        tier = _TIER_RANK.get(e.get("type"), 2)
        if hubs_only and tier >= 3:
            continue
        rows.append((0 if e.get("scheduled") else 1, tier, code))
    return [code for *_, code in sorted(rows)[:limit]]
