"""IATA code to city/country lookup, plus the airport-size signal discovery seeding uses.

The table is a committed build artifact (`data/airports.v3.json`), regenerated by
`data/build_airports.py` from OurAirports + Travelpayouts — same pattern as
`countries.json`. Everything here degrades to the bare IATA code if the file is missing,
so a cold checkout still runs.

An entry is `{city, country}` always, plus `{name, type, scheduled, lat, lon}` for a
real airport (metro codes like LON / NYC carry only city + country).
"""
from __future__ import annotations

import json
import threading
from typing import Any

from config import DATA_DIR

_TABLE_FILE = DATA_DIR / "airports.v3.json"

_lock = threading.Lock()
_index: dict[str, dict[str, Any]] | None = None


def load() -> dict[str, dict[str, Any]]:
    global _index
    with _lock:
        if _index is None:
            try:
                _index = json.loads(_TABLE_FILE.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                _index = {}
        return _index


# Full ISO 3166-1 alpha-2 -> {name, continent, subregion}, derived from mledoze/countries
# with travel-taxonomy overrides. Regenerate with `py -3 data/build_countries.py`.
_COUNTRIES_FILE = DATA_DIR / "countries.json"
_countries: dict[str, dict[str, str]] | None = None


def _country_table() -> dict[str, dict[str, str]]:
    global _countries
    if _countries is None:
        try:
            _countries = json.loads(_COUNTRIES_FILE.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            _countries = {}
    return _countries


def country_name(code: str) -> str:
    return _country_table().get((code or "").upper(), {}).get("name", "")


def region_of(code: str) -> tuple[str, str]:
    """(continent, subregion) for an ISO alpha-2 country code, or ('', '') if unknown."""
    entry = _country_table().get((code or "").upper())
    return (entry["continent"], entry["subregion"]) if entry else ("", "")


def taxonomy() -> list[dict[str, Any]]:
    """The region tree: continents -> subregions -> countries, for /api/regions."""
    tree: dict[str, dict[str, list[dict[str, str]]]] = {}
    for code, e in _country_table().items():
        cont, sub = e["continent"], e["subregion"]
        if cont in ("", "Antarctic"):
            continue
        tree.setdefault(cont, {}).setdefault(sub, []).append({"code": code, "name": e["name"]})
    return [
        {
            "continent": cont,
            "subregions": [
                {"name": sub, "countries": sorted(cs, key=lambda c: c["name"])}
                for sub, cs in sorted(subs.items())
            ],
        }
        for cont, subs in sorted(tree.items())
    ]


def describe(code: str) -> dict[str, Any]:
    entry = load().get((code or "").upper())
    if not entry:
        return {"city": (code or "").upper(), "country": ""}
    return entry


# Best-hub-first ordinal for discovery seeding. A metro code (LON, NYC) has no `type`
# and sorts with the mediums — it is still a fine thing to probe.
_TIER_RANK = {"large": 0, "medium": 1, "small": 3}


def shortlist(country_codes: "Any", limit: int = 40, hubs_only: bool = True) -> list[str]:
    """IATA codes in the given ISO alpha-2 countries, best hubs first.

    Discovery seeding (`board._seed_candidates`) probes this list for a live fare when the
    board provider's own discovery returns too few destinations inside a region filter.
    Ordered by scheduled service, then airport size; one code per airport, capped at
    `limit` so the probe stays cheap. `hubs_only` drops the small airstrips — nobody flies
    a board-worthy international trip from those, and probing them just wastes calls.
    """
    want = {(c or "").upper() for c in country_codes}
    if not want:
        return []
    rows = []
    for code, e in load().items():
        if e.get("country") not in want:
            continue
        tier = _TIER_RANK.get(e.get("type"), 2)
        if hubs_only and tier >= 3:
            continue
        rows.append((0 if e.get("scheduled") else 1, tier, code))
    return [code for *_, code in sorted(rows)[:limit]]
